package com.chris.tim3r

interface ListOfQuotesInterface {
    fun getQuote(): Quotes
}
class ListOfQuotes: ListOfQuotesInterface {

    private var rand: Int = 0

    private val quotes: List<Quotes> = listOf(
        Quotes("The best way out is always through",
            "– Robert Frost"),
        Quotes("I know for sure that what we dwell on is who we become",
            "– Oprah Winfrey"),
        Quotes("You must be the change you want to see in the world",
            "– Mahatma Gandhi"),
        Quotes("Failure is the condiment that gives success its flavor",
            "– Truman Capote"),
        Quotes("Vision without action is daydream. Action without vision is nightmare",
            "– Japanese Proverb"),
        Quotes("Success consists of doing the common things of life uncommonly well",
            "- Unknown"),
        Quotes("Experience is what you get when you don’t get what you want",
            "– Dan Stanford"),
        Quotes("Remember that happiness is a way of travel, not a destination",
            "– Roy Goodman"),
        Quotes("We judge of man’s wisdom by his hope",
            "– Ralph Waldo Emerson"),
        Quotes("The surest way not to fail is to determine to succeed",
            "– Richard B. Sheridan"),
        Quotes("Act or accept",
            "– Anonymous"),
        Quotes("Fall down seven times, get up eight",
            "-Â Japanese Proverb"),
        Quotes("The best way to predict the future is to create it",
            "- Unknown"),
        Quotes("Attitudes are contagious. Make yours worth catching",
            "- Unknown"),
        Quotes("Do not let what you cannot do interfere with what you can do",
            "– John Wooden"),
        Quotes("Sooner or later, those who win are those who think they can",
            "– Richard Bach"),
        Quotes("Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better",
            "– Samuel Beckett"),
        Quotes("Cause Change & Lead\n" +
                "Accept Change & Survive\n" +
                "Resist Change & Die",
            "– Ray Norda, Chairman, Novell"),
        Quotes("An obstacle is often a stepping stone",
            "– Prescott"),
        Quotes("Life is “trying things to see if they work",
            "- Ray Bradbury"),
        Quotes("Life is 10% what happens to us and 90% how we react to it",
            "- Dennis P. Kimbro"),
        Quotes("Where the willingness is great, the difficulties cannot be great",
            "- Machiavelli."),
        Quotes("You are what you think about all day long",
            "— Dr. Robert Schuller"),
        Quotes("What you do speaks so loudly that I cannot hear what you say",
            "— Ralph Waldo Emerson”"),
        Quotes("Talent is formed in solitude, character in the bustle of the world",
            "– Johann Wolfgang von Goethe"),
        Quotes("To avoid criticism do nothing, say nothing, be nothing",
            "– Elbert Hubbard"),
        Quotes("The art of being wise is the art of knowing what to overlook",
            "– William James"),
        Quotes("Sometimes even to live is an act of courage",
            "– Seneca"),
        Quotes("Do first things first, and second things not at all",
            "– Peter Drucker"),
        Quotes("Defeat is not bitter unless you swallow it",
            "– Joe Clark"),
        Quotes("Positive anything is better than negative thinking",
            "-Â Elbert Hubbard"),
        Quotes("Those who wish to sing, always find a song",
            "-Â Swedish Proverb"),
        Quotes("If you’re going through hell, keep going",
            "-Â Winston Churchill"),
        Quotes("Life is a shipwreck but we must not forget to sing in the lifeboats",
            "-Â Voltaire"),
        Quotes("There is no education like adversity",
            "– Disraeli"),
        Quotes("He who has a why to live can bear almost any how",
            "– Friedrich Nietzsche"),
        Quotes("Adversity introduces a man to himself",
            "– Author Unknown"),
        Quotes("Have the passion, take the action & magic will happen",
            "– Bar Rafaeli"),
        Quotes("If you’ve got it. use it. If you don’t got it, then get it",
            "- Unknown"),
        Quotes("Faith held solely is the begining of action",
            "- Unknown"),
        Quotes("Positivity is all about overlooking the negative fact",
            "- Unknown"),
        Quotes("Life is all about up and doing",
            "- Unknown"),
        Quotes("You will never get lessons on swimming from a drowning man",
            "– unknown"),
        Quotes("If you can’t sleep do not count the sheep, worship the Shepherd",
            "– Babsie Burke"),
        Quotes("Life is a journey, its not a race. Walk through it",
            "- Unknown"),
        Quotes("The measure of who we are is what we do with what we have",
            "– Sandiso"),
        Quotes("Better to understand a little than to misunderstand a lot",
            "- Unknown"),
        Quotes("Opportunity isn’t knocking coz you haven’t built the doors yet",
            "- Unknown"),
        Quotes("Man is the only living being who cuts trees, makes paper, and writes \"SAVE TREES\" on it",
            "- Unknown"),
        Quotes("If money doesn’t grow on trees why do bank have branches?",
            "- Unknown"),
        Quotes("People tend to make rules for others and exceptions for themselves",
            "- Unknown"),
        Quotes("Always and never are two words you should always remember never to use",
            "- Unknown"),
        Quotes("All is well that ends",
            "- Unknown"),
        Quotes("Three may keep a secret, if two of them are dead",
            "- Unknown"),
        Quotes("If you steal from one author, it’s plagiarism; if you steal from many, its research",
            "- Unknown"),
        Quotes("Common sense is not so common",
            "- Unknown"),
        Quotes("Always borrow money from a pessimist. He won’t expect it back",
            "- Unknown"),
        Quotes("When your only tool is a hammer, all problems start looking like nails",
            "- Unknown"),
        Quotes("Consciousness: that annoying time between naps",
            "- Unknown"),
        Quotes("Work in silence, let your success speak",
            "- Unknown"),
        Quotes("Hard work has a future payoff. – Laziness pays off now",
            "- Unknown"),
        Quotes("Everyone has a photographic memory. Some don’t have film",
            "- Unknown"),
        Quotes("Change is good, but dollars are better",
            "- Unknown"),
        Quotes("Eagles may soar, but weasels don’t get sucked into jet engines",
            "- Unknown"),
        Quotes("I am not fat, I am just easier to see",
            "- Unknown"),
        Quotes("Love may be blind but marriage is a real eye-opener",
            "- Unknown"),
        Quotes("Take my advice — I’m not using it",
            "- Unknown"),
        Quotes("If the music’s too loud you’re too old",
            "- Unknown"),
        Quotes("If you cannot convince them, confuse them",
            "- Unknown"),
        Quotes("I fell in love at first sight. I should have looked twice",
            "- Unknown"),
        Quotes("I fell in love at first sight. I should have looked twice",
            "- Unknown"),
        Quotes("The smallest changes make the biggest difference",
            "- Unknown"),
        Quotes("If Plan A doesn’t work, the alphabet has 25 more letters. Keep calm",
            "- Unknown"),
        Quotes("Everybody wants to go to heaven, but nobody wants to die",
            "- Unknown"),
        Quotes("Life is like a bird, it’s pretty cute until it shits on your head",
            "- Unknown"),
        Quotes("We live in an age where pizza gets to your home before police",
            "- Unknown"),
        Quotes("Magnify you Skills…or else modify your Goals",
            "- Unknown"),
        Quotes("A bad plan is better than no plan",
            "- Unknown"),
        Quotes("War does not determine who is right – only who is left",
            "- Unknown"),
        Quotes("The one who decides to wipe the tears of the poor must have the money to buy the tissue…",
            "- Unknown"),
        Quotes("Keep the dream alive: Hit the snooze button",
            "- Unknown"),
        Quotes("Only dead fish go with the flow",
            "- Unknown"),
        Quotes("Wise people think all they say, fools say all they think",
            "- Unknown"),
        Quotes("Failure is not falling down, it is not getting up again",
            "- Unknown"),
        Quotes("The greatest risk is to risk nothing at all",
            "- Unknown"),
        Quotes("Assumption is the mother of all screw-ups",
            "- Unknown"),
        Quotes("Your true value depends entirely on what you are compared with",
            "- Unknown"),
        Quotes("Failure teaches success",
            "- Unknown"),
        Quotes("I pretend to work. They pretend to pay me",
            "- Unknown"),
        Quotes("The early bird gets the worm, but the second mouse gets the cheese",
            "- Unknown"),
        Quotes("Every man is the architect of his own fortune",
            "- Unknown"),
        Quotes("I don’t have an attitude problem. You have a perception problem",
            "- Unknown"),
        Quotes("Wise men make proverbs, but fools repeat them",
            "- Unknown"),
        Quotes("I don’t have a bad handwriting. I have my own font",
            "- Unknown"),
        Quotes("If everything seems to be coming your way, you’re probably in the wrong lane",
            "- Unknown"),
        Quotes("I am not arguing. I am simply explaining why I’m right",
            "- Unknown"),
        Quotes("The worst distance between two people is misunderstanding",
            "- Unknown"),
        Quotes("Nothing grows without some rainy days",
        "- Unknown"),
        Quotes("Increase the quality of words, not their volume.\n Because flowers grow from rain, not from thunder",
        "- Unknown")
    )

    override fun getQuote(): Quotes {
        var random = (0 until (quotes.size - 1)).random()
        while (rand == random) {
            random = (0 until (quotes.size - 1)).random()
        }
        rand = random
        return quotes[rand]
    }

}